; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.embed_txtfiles = certs/ca_cert.pem

; Optimization flags to reduce firmware size (remove conflicting defines)
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -Os
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -DCONFIG_FREERTOS_ASSERT_DISABLE=y
    -DNDEBUG
    
; Reduce partition table size    
board_build.partitions = min_spiffs.csv